sudo: required
dist: trusty

language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.9 main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost-all-dev llvm-3.9-dev

script:
    - cmake -G "Unix Makefiles" .
    - make
    - make check
