sudo: required
dist: trusty

language: cpp

compiler:
    - clang
    - gcc

before_install:
    - if [ $CC == "gcc" ]; then sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'; fi
    - if [ $CC == "clang" ]; then sudo add-apt-repository -y 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'; fi
    - sudo apt-get update -qq
    - sudo apt-get install -y libedit-dev g++-multilib lcov
    - if [ $CC == "gcc" ]; then
          sudo apt-get install -y gcc-5 g++-5;
          export CXX="g++-5" CC="gcc-5" CXXFLAGS="-coverage";
      fi
    - if [ $CC == "clang" ]; then
          sudo apt-get install -y clang-3.9;
          export CXX="clang++-3.9" CC="clang-3.9";
      fi
    - wget http://releases.llvm.org/5.0.0/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz
    - tar -xvf clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz
    - pip install --user lit cpp-coveralls

script:
    - set -e # Error out immediately if any of the following commands fails.
    - cmake -G "Unix Makefiles"
      -DCMAKE_PREFIX_PATH=$PWD/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04
      -DCMAKE_CXX_FLAGS="$CXXFLAGS" -DCMAKE_BUILD_TYPE=Debug .
    - make
    - make check
    - if [ $CXX == "g++-5" ]; then
          make coverage;
      fi

after_success:
    - if [ $CXX == "g++-5" ]; then
          coveralls --exclude clang+llvm-5.0.0-linux-x86_64-ubuntu14.04 --exclude CMakeFiles --exclude src/yaml-cpp;
      fi
