sudo: required
dist: trusty

language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost-all-dev

script:
    - cmake -G "Unix Makefiles" .
    - make
    - make check
