sudo: required
dist: trusty

language: cpp

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost-all-dev g++-multilib lcov
    - wget http://releases.llvm.org/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    - tar -xvf clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    - pip install --user cpp-coveralls

script:
    - cmake -G "Unix Makefiles"
      -DCMAKE_PREFIX_PATH=$PWD/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04
      -DCMAKE_CXX_FLAGS="-coverage" -DCMAKE_BUILD_TYPE=Debug .
    - make
    - make check
    - if [ $CC != "clang" ]; then
          make coverage;
      fi

after_success:
    - if [ $CC != "clang" ]; then
          coveralls --exclude clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04 --exclude CMakeFiles;
      fi
