sudo: false
dist: trusty

language: cpp

matrix:
    include:
        - compiler: clang
          addons:
              apt:
                  sources:
                      - llvm-toolchain-trusty
                  packages:
                      - clang-3.9
                      - libedit-dev

        - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-5
                      - g++-5
                      - libedit-dev
                      - lcov

before_install:
    - if [ $CXX == "clang++" ]; then export CXX="clang++-3.9"; fi
    - if [ $CXX == "g++" ]; then export CC="gcc-5" CXX="g++-5" CXXFLAGS="-coverage"; fi

install:
    - wget http://releases.llvm.org/5.0.0/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz
    - tar -xvf clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz
    - pip install --user lit cpp-coveralls

script:
    - set -e # Error out immediately if any of the following commands fails.
    - cmake -G "Unix Makefiles"
      -DCMAKE_PREFIX_PATH=$PWD/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04
      -DCMAKE_CXX_FLAGS="$CXXFLAGS" -DCMAKE_BUILD_TYPE=Debug .
    - make
    - make check
    - if [ $CXX == "g++-5" ]; then
          make coverage;
      fi

after_success:
    - if [ $CXX == "g++-5" ]; then
          coveralls --exclude clang+llvm-5.0.0-linux-x86_64-ubuntu14.04 --exclude CMakeFiles --exclude src/yaml-cpp;
      fi
